### PR TITLE
Use base fixture from tar to prevent permission problems

### PR DESCRIPTION
**Pull request by Vampire**
At least on Cygwin there were problems when the files in the base fixture were
created by a Git checkout, as Git does not care about permissions besides
executable flag.
But for the SVN repo properly functioning, permissions seem to be crucial.
So now the base fixture is extracted from a tar archive instead.

### CODE REVIEW

**Comment by Vampire** [comment]
@tnyblom do you prefer the single PRs I posted now and I rebase after you merged (because conflicts in test files), or do you want me to combine all in one PR?

**Comment by tnyblom** [comment]
@Vampire What ever you like :)

**Comment by Vampire** [comment]
Well, I'm currently done with changes, unless I find another bug during the conversion I'm currently doing. :-)

**Comment by Vampire** [comment]
Argh, please wait with further merges, except for this one here which is safe.
I combined my PRs and used it and it greatly misbehaves.
I'll investigate later where I fucked up.

**Comment by Vampire** [comment]
You can continue merging my PRs, the one that breaks it is #96 and I pushed a test that fails so you do not merge it accidentally.
Btw. in the settings of the GitHub repo you can require that the check be successful for merging.

**Comment by Vampire** [comment]
Ok, #96 should be correct too now. :-)

**Comment by damianb** [comment]
FWIW, this PR causes all tests to fail when building a docker image using the dockerfile in the repository.  It appears that the version of `tar` that ships with Debian 8.11 is too old to support such a feature.

**Comment by damianb** [comment]
Actually, looking further, it looks like the tests were never utilized in conjunction with the dockerfile at all.  Nevermind me!

**Pull request merged**
